// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dvdytmrncxyewlliauky.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR2ZHl0bXJuY3h5ZXdsbGlhdWt5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE2MzE5MjIsImV4cCI6MjA1NzIwNzkyMn0.5BCmrH-AavT8yWNnmMOfr-tWgbGboNGaxVFl1bCLdqQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);